name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main # Trigger saat ada PR ke branch main
  push:
    branches:
      - main # Trigger saat ada perubahan (merge/commit) ke branch main

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Java 8
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      # Step 3: Build aplikasi JAR menggunakan Maven
      - name: Build JAR file
        run: mvn clean package -DskipTests=true

  push-docker:
    name: Build and Push Docker Image
    needs: build # Menunggu job build selesai
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # Hanya trigger saat ada perubahan di branch main

    steps:
      # Step 1: Checkout kode dari repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }} # Docker Hub password

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/credit-simulator:latest .

      # Step 4: Push Docker Image
      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/credit-simulator:latest
