name: Build and Push Docker Image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build JAR file
        run: mvn clean package -DskipTests=true

      - name: Move JAR file to root
        run: cp app/application/target/credit-simulator-application-1.0.0-jar-with-dependencies.jar credit_simulator.jar

  push-docker:
    name: Build and Push Docker Image
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/credit-simulator
          VERSION=$(date +'%Y%m%d%H%M%S')
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION .
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Push Docker Image to Docker Hub
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/credit-simulator
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ env.VERSION }}
